### ISSUE TITLE
_serverUrl: unbound variable in freqstart.sh and permission issue

### ISSUE THREAD

**Issue by lsiem** [berndhofer/freqstart#24]
When I follow the installation steps and enter the command `./freqstart.sh --setup`  to install, I get the following error message:
`./freqstart.sh: line 2057: _serverUrl: unbound variable`

Additionally when not running with root privileges, I get the following error message:
`rm: cannot remove '/tmp/freqstart/freqstart.lock': Permission denied`

Thanks in advance!

**Comment by berndhofer** [comment]
Thank you for your input!

Both should be fixed in v.0.1.5 which i hope i can get ready today in the afternoon.

**Comment by berndhofer** [comment]
Fixed in v0.1.5
