### ISSUE TITLE
nginx permission issue

### ISSUE THREAD

**Issue by lsiem** [berndhofer/freqstart#26]
When the script configures nginx, the following error appears:

`./freqstart.sh: line 1422: /etc/nginx/conf.d/frequi.conf: Permission denied
Error in freqstart.sh in function _fsSetupNginxConf_ on line 1422
`

**Comment by berndhofer** [comment]
Oh okay, seems that i've to sudo printf files. Thank you!

**Comment by berndhofer** [comment]
Fixed in v0.1.6
