### ISSUE TITLE
DockerException (permission denied)

### ISSUE THREAD

**Issue by lsiem** [berndhofer/freqstart#29]
`docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Error in freqstart.sh in function _fsSetupFreqtrade_ on line 1062
`
Running docker commands as root should fix this issue altough a better approach would be to add the user to the docker group but this requires the user to re-login which interrupts the script

**Comment by berndhofer** [comment]
Ive two routines in the pipeline. 1. create user if root is detected and copy files to new home dir and 2. add user to docker group. This could be initially done in the setup routine which would cause an interruption for server updates anyways. Let me know what you think.

**Comment by berndhofer** [comment]
Should be interactive, if someone just wants to stay on the root user.

**Comment by lsiem** [comment]
> Ive two routines in the pipeline. 1. create user if root is detected and copy files to new home dir and 2. add user to docker group. This could be initially done in the setup routine which would cause an interruption for server updates anyways. Let me know what you think.

Yes you could seperate the shell scripts (pre-setup (for user and permission management) and then adding installation script to autostart in the pre-setup script.

**Comment by berndhofer** [comment]
I want it all in one script. Routine added to v0.1.6 but I have to utilize "reboot" to force the logout since pkill on root is suicide. Leave this issue open for further suggestions.

**Comment by lsiem** [comment]
Maybe using the `newgrp` command might solve the issue
[newgrp](https://www.ibm.com/docs/en/aix/7.1?topic=n-newgrp-commandl)

**Comment by berndhofer** [comment]
Im unsure if "su -l $newuser" would be enough for the root detection routine to apply everything, but i added "sudo newgroup" to the group verification routine of the current user.

**Comment by berndhofer** [comment]
Implemented in v0.2.0, Thank you!
