### ISSUE TITLE
Script interrupt after logging into root account

### ISSUE THREAD

**Issue by lsiem** [berndhofer/freqstart#41]
When you start the script for the first time, you will be logged into the root account. 
The script will not run until you enter `exit` or start the script again after deleting the `/tmp/freqstart` folder.

**Comment by berndhofer** [comment]
It shouldnt log you into root but the new created user. I forgot to remove the tmp file before which includes the scriptlock, which results in an error so the script cant be run twice at the some time, but that should be resolved in v1.0.0. Thank you for testing, much appreciated!
