### ISSUE TITLE
Domain with SSL error

### ISSUE THREAD

**Issue by lsiem** [berndhofer/freqstart#54]
When running the script with the setup routine and choosing `Domain with SSL (truecrypt)` on the question how to access FreqUI, the following error occurs:

`The domain example.com does not point to "". Review DNS and try again!`

**Comment by berndhofer** [comment]
Can you exec ```dig +short myip.opendns.com @resolver1.opendns.com``` and see if you get a response?

**Comment by lsiem** [comment]
Unfortunately I do not get any response. When entering a domain such as `google.com` I get the same error

**Comment by berndhofer** [comment]
Implemented the needed package in v2.0.0
