### ISSUE TITLE
Error running freqstart on Oracle vps

### ISSUE THREAD

**Issue by tomjrtsmith** [berndhofer/freqstart#58]
mkdir: cannot create directory ‘/freqstart/docker’: Permission denied
Error in freqstart.sh in function _fsPkgs_ on line 2886

Ubuntu 22.04 Minimal

**Comment by tomjrtsmith** [comment]
I think  

mkdir -p "${FS_DIR_DOCKER}"

should be 

sudo  mkdir -p "${FS_DIR_DOCKER}"

**Comment by berndhofer** [comment]
Added in v2.0.0; you earned your thanks in the code 👍
