### ISSUE TITLE
Certbot failed to authenticate some domains (authenticator: webroot).

### ISSUE THREAD

**Issue by tomjrtsmith** [berndhofer/freqstart#80]
Unsure what may have caused this other than selecting No (N) when it asked if I would share my email address with Certbot. This dialogue didn't appear again when I re-ran Freqstart.  

+ Compose project: freqstart_nginx.yml
  Image is up-to-date: amd64/nginx:stable
  Image is up-to-date: certbot/certbot:latest
Creating network "freqstart_nginx_default" with the default driver
Creating freqstart_nginx_domain ... done

+ Container: freqstart_nginx_domain
? Update container automatically (recommended)? (y/n) y
  Image is up-to-date: amd64/nginx:stable

+ Validate project: freqstart_nginx.yml
  [SUCCESS] Container is active: freqstart_nginx_domain

+ Run project: freqstart_nginx.yml
  Image is up-to-date: amd64/nginx:stable
  Image is up-to-date: certbot/certbot:latest
Creating freqstart_nginx_freqstart_certbot_run ... done
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for xxx.xxxxxx.io

Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: xxx.xxxxx.io
  Type:   connection
  Detail: xxx.xxx.xxx.xxx: Fetching http://xxx.xxxxx.io/.well-known/acme-challenge/PH8-T8FRWJyvsgXtxyXCnfX__cMJZkBOKw7qiflqA-4: Error getting validation data

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: 1

+ Compose project: freqstart_nginx.yml
  Image is up-to-date: amd64/nginx:stable
  Image is up-to-date: certbot/certbot:latest
Recreating freqstart_nginx_domain ... done

+ Container: freqstart_nginx_domain
  Automatic update is activated.
  Image is up-to-date: amd64/nginx:stable

+ Validate project: freqstart_nginx.yml
! [WARNING] Container is not active: freqstart_nginx_domain

! [ERROR] Nginx container is not running. Restart Nginx setup!

**Comment by berndhofer** [comment]
The email doesn't matter. Either it's a proxy pass problem, volume path failure, or the ufw firewall or your oracle firewall.

**Comment by berndhofer** [comment]
Also, can you delete the /script/etc folder so there aren't any permission errors and re-run the setup.

**Comment by tomjrtsmith** [comment]
I deleted /script/etc, re-ran setup and it failed again. This is the second
server I'm deploying using freqstart with domain authentication and ssl.
Freqstart can't find the third domain (that is an ARM chip VPS) and my DNS
provider (namecheap) have asked some questions about the ssl setup.

**Comment by berndhofer** [comment]
The ssl setup is letsencrypt (https://letsencrypt.org/) and it just needs a valid IPv4 A-record pointed to the host, but that's not the problem or you wouldn't come to that part. The email is also optional to letsencrypt as it just sends notifications like expiry warnings. The problem here is that letsencrypt can't reach the acme-challenge folder wich is a) not created because of permission error or b) not reachable to letsencrypt because of a wrong path in the proxy pass conf for nginx or c) some oracle VPS related problem.

**Comment by tomjrtsmith** [comment]
I restarted the instance and the reinstall went through without a hitch.
