### ISSUE TITLE
Login failed.

### ISSUE THREAD

**Issue by tomjrtsmith** [berndhofer/freqstart#82]
Same login error occurs on two vps's installed using Freqstart using the example strategy DoesNothingStrategy from the default install.

' Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to https://xxx.xxxxx.xx/freqstart/example/api/v1/ping to make sure the bot API is reachable '

I can see when I run htop the process running the bot is running on both vps instances, passwords seem to be where they should be in json files. I haven't yet started any custom strategies from docker files, simply installed Freqstart and logged into FreqUI through NGIX using the password from the install. From there FreqUI doesn't seem to accept any password for any API url I can think of.

**Comment by berndhofer** [comment]
Usage error as you wouldn't see the freqstart folder part if you would have accessed the main frequi container with the setup URL.

**Comment by tomjrtsmith** [comment]
That's neither providing an answer nor helping me log in. If I change it from freqstart/example to /DoesNothingStrategy it brings up a pre-populated login box that won't let me log in either. I re-ran setup and entered the example API url from the setup script and re-entered my passwords to make sure I hadn't missed something in a config.json file that I didn't know about, no luck with that either. So I can't log in... could it be something in the NGIX setup blocking the password?
